### ISSUE TITLE
Replace references to "native token" with "internal token"

### ISSUE THREAD

**Issue by kronosapiens** [JoinColony/Colony-Whitepaper#20]
Too much d r a m a.

**Comment by elenadimitrova** [comment]
What's wrong with "native token"? We use that term (admittedly mainly in discussions than code) to signify Colony's own token. How does "internal" better carry across that meaning?

**Comment by kronosapiens** [comment]
My understanding is that "native" token along with "colony" plays too heavily into the imperialist connotation, which it seems we are trying to distance ourselves from. I personally don't feel strongly about it, if we'd like to have a larger discussion.

**Comment by elenadimitrova** [comment]
Hmm makes sense. Considering there are only 2 instances I can find of "native token" in the WP, and they are both preceded by " Colony own", can we just omit anything further? So "Colony own token" and leave it there?

**Comment by kronosapiens** [comment]
Works for me 🤙

**Comment by kronosapiens** [comment]
Closed by #22
