### ISSUE TITLE
Can we use Patricia Trees?

### ISSUE THREAD

**Issue by area** [JoinColony/Colony-Whitepaper#3]
*We need to decide whether we're going to use tries or trees. But that's [bikeshedding](https://en.wikipedia.org/wiki/Law_of_triviality) so let's skip over that for now.*

Currently, as described, reputation mining revolves around Merkle trees. However, in the event of a successful Colony Network, it would be much more efficient for miners to be able to use Patricia Trees. An implementation [already exists](https://github.com/chriseth/patricia-trie), too. The fundamental benefit of the Patricia tree, aside from this efficiency, is that they only depend on the state, not the order in which the tree was constructed, which is currently the case for our Merkle trees.

*Aside: why does it matter what they use? To avoid a consensus failure, I have an overwhelming desire for the code used to create the Reputation Root Hash to be the same as the code used to determine what the correct Reputation Root Hash is in the event of a dispute, which suggests Solidity. If we're running a local chain to build our tree, then the space required for the Merkle tree described in the paper is going to be much larger than the space required for a hypothetical Patricia tree where the key is e.g. ColonyAddressUserAddressSkillID, as there will little-to-no redundant data stored*

Unfortunately, I cannot see a way past an issue that arises if you use a Patricia Tree during the dispute resolution process. Fundamentally, we need an order in order to decay existing reputations, and that order needs to be accessible on-chain (so that we know which reputation they were meant to update during that calculation, and we can calculate it ourselves. In the case of the Merkle tree, this essentially comes from the path of the leaf. There is no obvious such equivalent for the Patricia Tree, and I am having great difficulty finding a cunning workaround.

**Comment by area** [comment]
To be clear, the best non-cunning workaround I've come up with is to simply put an extra property on every leaf that represents how many leaves were in the tree when it was first added.

**Comment by kronosapiens** [comment]
@area can you confirm that the current reputation tree implementation is along the lines you mention here?

Looking at the [miner client](https://github.com/JoinColony/colonyNetwork/blob/develop/packages/reputation-miner/ReputationMiner.js#L587) I'm seeing the `uid` of the reputation being stored as part of the value so it seems like it, but please confirm before I make any edits to the WP since this issue 18 months old.

**Comment by area** [comment]
Yeah, this is effectively what that UID is.
