### ISSUE TITLE
Implementation updates

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/Colony-Whitepaper#7]
Here we list changes that are a result of implementing the white paper (see work in `JoinColony/colonyNetwork` repo). These are grouped by corresponding section to ease updates so insert in appropriate order.

- [x] **6.2.1 Reputation change from contributing to a task**

- Specify the reputation earned by Task evaluator, e.g. For the purposes of calculating earned reputation the rating of the evaluator is assumed to be the same as the maximum of that of a manager, i.e. a `5`.
- Be explicit about the domain or skill where reputation is earned i.e for manager and evaluator: domain rep for worker domain + skill rep.

- [x] **7.4 Submission of a new root hash**

- Use the `uint256` converted keccak256 hash for comparison to target in `keccak256(address, N, hash) < target`
- In "Who can submit a new root hash?" section the following is actually implemented so that the target increases to that maximum in the space of an hour rather than 150 blocks.
>At the beginning of the submission window, the target is set to 0 and slowly increases to 2^256 - 1 after 150 blocks

- [x] WP says that stake is divided by 10**15 to determine `N`. In fact, it is divided by the `MIN_STAKE` which is `2000 * WAD == 2000 * 10**18`

- [x] **7.8 Costs and Rewards of mining**

-  "Finally, this transaction also makes the miners eligible to claim their CLNY token reward." - there is no such claim process. Rewards for mining are immediately reinvested.

**Comment by filiplazovic** [comment]
Right now, only changes up to 10% are allowed. There is a requirement for larger changes in https://github.com/JoinColony/colonyNetwork/issues/27, which would require token weighted voting. Since we are not implementing token weighted voting for the MVP, we should decide whether we should allow owner to change issuance rate without constraints. Update **5.1.3** if needed.

**Comment by kronosapiens** [comment]
Note that after discussing with @elenadimitrova we would like to add a new rule saying that submissions for reputation root hashes are open until an hour has passed AND a submission has been received.

**Comment by kronosapiens** [comment]
@elenadimitrova Do you still propose making explicit the casting of the keccak output to a uint256?

I feel like `uint256(keccak256(address, N, hash)) < target` is a bit clunky and `keccak256(address, N, hash) < target` is sufficiently clear, but I can make the change if you feel strongly.

**Comment by elenadimitrova** [comment]
We are explicit in the code here
`require(uint256(getEntryHash(msg.sender, entryIndex, newHash)) < target, "colony-reputation-mining-cycle-submission-not-within-target");` and would prefer to match that.

Also we are now using `keccak256(abi.encodePacked(address, N, hash)..` which is why in code it's broken down into separate calls. Not too fussed about including `abi.encodePacked` although it is different to `abi.encode` so perhaps worth mentioning?

**Comment by kronosapiens** [comment]
Will roll @filiplazovic 's comment into a new issue which covers extension contracts and not-yet-implemented functionality.
