### ISSUE TITLE
Skills / Domains representation discrepancies & notes

### ISSUE THREAD

**Issue by lsenta** [JoinColony/Colony-Whitepaper#9]
- [x] **6.3 On-chain representation of skills and domains**

The `parent_n_id` line in
https://github.com/JoinColony/Colony-Whitepaper/blob/master/reputation/reputation.tex#L69-L82

evolved into an array
https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/ColonyNetworkStorage.sol#L47

We should have something like:
> `parents[...]`: array of ancestors where parents[i] is the (i ^ 2)th ancestor of the node. parents[0] is the direct ancestor.

---

I found the description & code somehow confusing, a few notes on what I understood:

Skills / Domains are Tree of Nodes.
Each node has a pointer to its parent (`s.parents[0]`), this is how we represent the tree hierarchy.

In the end this is just a regular Tree with a few fields used for optimisation / caching.

- the `children[]` field contains EVERY children (recursive) of this Node
  - It's used to speed-up Nested Set Operations ("get all children"),
  - [ ] The usual terminology would be `descendants`.
- The `parents[i]` field contains `ancestor(i ^ 2)`
  - It's used to speed-up navigation Operations ("find nth ancestor"),
  - [ ] The usual terminology would be `ancestors` or even `ancestors_cache`.
- We store the total number of parents and the total number of children
  - [ ] `nParents` doesn't relate to `parents` the same way than `nChildren` relates to `children` maybe use a different naming to avoid confusion,
  - [ ] The usual terminology for `nParents` would be `depth`.

- [x] Maybe add a few more nodes on the Domain tree from `4.2 Domains` (p.10) so it doesn't look like a binary tree (the use of power of two with indexing got me confused).

**Comment by kronosapiens** [comment]
Working on this issue, but electing _not_ to change the naming on parents/children.
